[package]
name = "spl-universal-idl-program"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "0.9"
lazy_format = "2.0.0"
num-derive = "0.3"
num-traits = "0.2"
shank = "0.0.12"
solana-program = "1.9"
solana-security-txt = "1.1.0"
thiserror = "1.0.38"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]