[package]
name = "spl-uip-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"

[[bin]]
name = "spl-uip"
path = "src/bin/main.rs"

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
anyhow = "1.0.32"
solana-sdk = "1.13"
solana-program = "1.13"
solana-client = "1.13"
solana-cli-config = "1.13"
serde = { version = "1.0.122", features = ["derive"] }
spl-universal-idl-program = { path = "../program" }
flate2 = "1.0.25"
bincode = "1.3.3"
solana-clap-utils = "1.13"
serde_json = "1.0.91"
