name: Release

on push:
  branches:
    - master
  paths-ignore:
    - 'docs/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create tags
        id: create_tags
        run: |
          ci/tag-new-crates.sh
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
